print("*" * 30)
print(" " * 29 + "*")
print(" " * 29 + "*")
print("*" * 30)
print("*" + " " * 29)
print("*" + " " * 29)
print("**  " * 7 + "**")
print(" " * 29 + "*")
print(" " * 29 + "*")
print("*" * 30)
